# 🏠 Real Estate Estimator

🎯 In the following challenge, we will try to find if there is a ***LINEAR RELATIONSHIP*** between:
- the **price** of a flat (our **target** for each flat)
- and **features** such as surface area, number of bedrooms, etc.

❗️ Pandas is forbidden in this challenge ❗️

😁 Welcome to the [NumPy documentation](https://docs.scipy.org/doc/numpy/reference/), which will be your friend throughout this exercise.

👉 You can also find help in this [NumPy cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

In [1]:
# Load the NumPy library
import numpy as np

🌆 Suppose we have collected data from 4 flats:
- **features**:
    - `surface` (square feet)
    - `bedrooms`
    - `floors`
- **target**:
    - `price` (in thousands of USD)

|flats |surface (sq ft)|bedrooms|floors|price (k$)|
|------|-------------|--------|------|------------|
|flat1 |620|1|1|244|
|flat2 |3280|4|2|671|
|flat3 |1900|2|2|504|
|flat4 |1320|3|3|510|

👉 The first approach to **predict the price of a flat** is to try to **find a linear relationship between the target and the features** (*i.e. between price and (surface, bedrooms, floors)*), by solving the following **system of $n = 4$ linear equations with $p = 4$ unknown variables**:

$$\begin{cases}
    244 = \theta_0 + 620\theta_1 + 1\theta_2 + 1\theta_3 \\
    671 = \theta_0 + 3280\theta_1 + 4\theta_2 + 2\theta_3 \\
    504 = \theta_0 + 1900\theta_1 + 2\theta_2 + 2\theta_3 \\
    510 = \theta_0 + 1320\theta_1 + 3\theta_2 + 3\theta_3 \\
\end{cases}$$

which can be translated into a matrix equation:

$$\boldsymbol y = \boldsymbol {X \cdot \theta}$$

$$\begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix}_{4 \times 1} = \begin{bmatrix}
    1 & 620 & 1 & 1 \\
    1 & 3280 & 4 & 2 \\
    1 & 1900 & 2 & 2 \\
    1 & 1320 & 3 & 3
\end{bmatrix}_{4 \times 4} \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}_{4 \times 1}$$

where:
* $\boldsymbol y$ is the **`target`** vector, `Price`
* $\boldsymbol X$ represents the **`matrix of features`**
* $\boldsymbol {\theta} = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}$ (*theta*) is the vector of **coefficients/variables/unknowns** to be found

----

🤓 Here, we use the Greek letter `theta` $\boldsymbol \theta = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3 \\
\end{bmatrix}$ to represent the coefficients of our **features**:

- A flat with no surface, no bedrooms, and no floors costs $\theta_0$
- An increase of one square foot - *keeping the number of bedrooms and floor number constant* - increases the price by $\theta_1$ thousand USD
- An extra bedroom - *keeping the surface and floor number constant* - increases the price by $\theta_2$ thousand USD
- An increase in floor number - *keeping the surface and number of bedrooms constant* - increases the price by $\theta_3$ thousand USD

----

😉 If we manage to solve this system of linear equations (i.e. find $\theta_0$, $\theta_1$, $\theta_2$, $\theta_3$), the price of any new flat can be estimated using: $$y_{newflat} = \boldsymbol x_{newflat} \cdot \boldsymbol \theta$$

## (1) Define the `features` matrix $\boldsymbol X$:

❓ Create a $(4,3)$ `numpy.ndarray` storing the values of the 3 features (surface, bedrooms, floors) for the 4 observations.

In [7]:
X = np.array([
    [620,1,1],
    [3280,4,2],
    [1900,2,2],
    [1320,3,3]])

X

array([[ 620,    1,    1],
       [3280,    4,    2],
       [1900,    2,    2],
       [1320,    3,    3]])

❓ Double-check the ***shape***, ***size*** and ***dim*** of this ***np.array***

In [10]:
print(X.shape)
print(X.size)
print(X.ndim)
print(X.dtype)

(4, 3)
12
2
int64


❓ Add a "constant" vector of ones $ = \begin{bmatrix}
    1 \\
    1 \\
    1 \\
    1 \\
\end{bmatrix}$ to create the $(4,4)$ matrix $\boldsymbol X$ representing the system of linear equations

<details>
    <summary><i>Explanations</i></summary>

🤔 As you probably noticed, the system of linear equations involves a coefficient $\theta_0$ that appears in all 4 equations.

❗️ We need an additional feature to represent the y-intercept of the linear regression line

_Note_: We are talking about an [affine relation](https://math.stackexchange.com/questions/275310/what-is-the-difference-between-linear-and-affine-function) rather than a strictly linear one between `price` and features (_See Decision Science Module_)
    
</details>

In [11]:
# Define x0 as a (4,1) vector filled with ones using the fastest NumPy method
x0 = np.ones((4,1))
x0

array([[1.],
       [1.],
       [1.],
       [1.]])

In [12]:
# Use `numpy.hstack` to combine x0 with your previous (4,3) matrix to create the (4,4) matrix X
X = np.hstack((x0, X))
X

array([[1.00e+00, 6.20e+02, 1.00e+00, 1.00e+00],
       [1.00e+00, 3.28e+03, 4.00e+00, 2.00e+00],
       [1.00e+00, 1.90e+03, 2.00e+00, 2.00e+00],
       [1.00e+00, 1.32e+03, 3.00e+00, 3.00e+00]])

**🧪 Kodunu kontrol et!**

In [13]:
from nbresult import ChallengeResult

result = ChallengeResult('features',
    features=X
)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/yaren/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/yaren/code/ds_projects/data-real-estate-estimator/tests
plugins: anyio-4.12.1, dash-4.0.0, typeguard-4.4.2
collecting ... collected 3 items

test_features.py::TestFeatures::test_X_shape PASSED                      [ 33%]
test_features.py::TestFeatures::test_features_order PASSED               [ 66%]
test_features.py::TestFeatures::test_x0_is_ones PASSED                   [100%]

============================== 3 passed in 0.06s ===============================


💯 You can commit your code:

git add tests/features.pickle

git commit -m 'Completed features step'

git push origin master



## (2) Define the $\boldsymbol y$ vector of `Prices`

$\boldsymbol y  = \begin{bmatrix}
    244 \\
    671 \\
    504 \\
    510
\end{bmatrix}$

❓ What should the shape of $\boldsymbol y$ be to match our matrix notation $\boldsymbol y  = \boldsymbol {X\cdot \theta}$? Define $\boldsymbol y$ below. ❓

<details>
    <summary><i>Hint</i></summary>

$\boldsymbol y$ should be a $(4,1)$ array, the equivalent of a flat "vector" represented vertically
</details>

In [16]:
y = np.array([
    [244],
    [671],
    [504],
    [510]
])

print(y.shape)

(4, 1)


**🧪 Kodunu kontrol et!**

In [17]:
from nbresult import ChallengeResult

result = ChallengeResult('target',
    target=y
)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/yaren/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/yaren/code/ds_projects/data-real-estate-estimator/tests
plugins: anyio-4.12.1, dash-4.0.0, typeguard-4.4.2
collecting ... collected 1 item

test_target.py::TestTarget::test_shape PASSED                            [100%]

============================== 1 passed in 0.06s ===============================


💯 You can commit your code:

git add tests/target.pickle

git commit -m 'Completed target step'

git push origin master



## (3) Find the solution to the system

⏰ Now it's time to find the vector of coefficients $\boldsymbol \theta = \begin{bmatrix}
    \theta_0 \\
    \theta_1 \\
    \theta_2 \\
    \theta_3
\end{bmatrix}$!

👍 The solution to the equation is:
 
$$ \large \boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y 
\large \iff \boldsymbol X^{-1} \cdot \boldsymbol X \boldsymbol \cdot \theta = \boldsymbol X^{-1} \cdot \boldsymbol y 
\large \iff \boldsymbol \theta = \boldsymbol X^{-1} \cdot \boldsymbol y
$$

where $\large \boldsymbol X^{-1}$ is the inverse of $\large \boldsymbol X$.

In [18]:
# Compute the inverse of matrix X using the correct NumPy method
X_inverse = np.linalg.inv(X)
X_inverse

array([[ 1.64516129e+00, -7.51278738e-18, -2.90322581e-01,
        -3.54838710e-01],
       [-5.37634409e-04, -1.66950831e-19,  1.07526882e-03,
        -5.37634409e-04],
       [ 3.70967742e-01,  5.00000000e-01, -1.24193548e+00,
         3.70967742e-01],
       [-6.82795699e-01, -5.00000000e-01,  8.65591398e-01,
         3.17204301e-01]])

👉 You can verify the inverse works by testing the following identity:

$$\boldsymbol X^{-1} \cdot\boldsymbol X = \boldsymbol I_4$$
where $\boldsymbol I_4$ is the $4 \times 4$ identity matrix $ \begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1
\end{bmatrix}$

In [19]:
# Define I4 using the correct NumPy method
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

👉 Now compute $\boldsymbol X^{-1} \boldsymbol X$:

In [20]:
XinvX = X_inverse @ X
XinvX

array([[ 1.00000000e+00, -2.62012634e-13, -3.33066907e-16,
        -3.33066907e-16],
       [-1.08420217e-19,  1.00000000e+00, -1.08420217e-19,
         1.08420217e-19],
       [ 5.55111512e-17,  2.30482300e-13,  1.00000000e+00,
        -1.66533454e-16],
       [ 1.66533454e-16, -1.79856130e-13,  2.77555756e-16,
         1.00000000e+00]])

❓ Does it look like $\boldsymbol I_4$? ❓

⛔️ If not, you probably used the `*` operator to perform the multiplication between $\boldsymbol X^{-1}$ and $\boldsymbol X$. We want to do matrix multiplication here. Find the correct NumPy method (or shorthand operator) to do this.

✅ If yes, you may notice that the resulting product doesn't give you exactly zeros and ones. Try [`numpy.allclose()`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html?highlight=allclose#numpy.allclose) to verify your result:

In [21]:
np.allclose(XinvX, I4)

True

🎉 Finally, you can compute `theta` using the formula: $ \large \boldsymbol \theta = \boldsymbol X^{-1}\cdot \boldsymbol y $:

In [22]:
theta = X_inverse @ y
theta

array([[ 74.12903226],
       [  0.13655914],
       [-10.72580645],
       [ 95.93010753]])

**🧪 Kodunu kontrol et!**

In [23]:
from nbresult import ChallengeResult

result = ChallengeResult('solution',
    theta=theta
)
result.write()
print(result.check())


============================= test session starts ==============================
platform darwin -- Python 3.12.9, pytest-8.3.4, pluggy-1.5.0 -- /Users/yaren/.pyenv/versions/workintech/bin/python
cachedir: .pytest_cache
rootdir: /Users/yaren/code/ds_projects/data-real-estate-estimator/tests
plugins: anyio-4.12.1, dash-4.0.0, typeguard-4.4.2
collecting ... collected 2 items

test_solution.py::TestSolution::test_theta0_is_correct PASSED            [ 50%]
test_solution.py::TestSolution::test_theta_shape PASSED                  [100%]

============================== 2 passed in 0.06s ===============================


💯 You can commit your code:

git add tests/solution.pickle

git commit -m 'Completed solution step'

git push origin master



## (4) Predict the price of a new flat

You've finally solved the system and found $\boldsymbol \theta$, and you can now predict the `Price` (in thousands of $) of a 5th flat with these features:

- `Surface`: 3000 $ft^2$
- `Bedrooms`: 5 
- `Floors`: 1

using the formula:

$$y_{flat5} = \boldsymbol x_{flat5} \cdot \boldsymbol \theta$$

In [24]:
# Define x5

x5 = np.array([
    [1, 3000, 5, 1]
])

# Compute y5

y5 = x5 @ theta
y5

# You should find a price of $526,000

array([[526.10752688]])

## (5) Reality Check

❗️ In reality, the price of a flat is never fully determined by its surface, number of bedrooms, and floor number alone.

Imagine we measured the real $y_{flat5}$ price as $700,000 instead of the predicted $526,000.

🤨 Can we take this new information into account to improve our model?

❓ Update the system of linear equations $ \large \boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y$ to include the data from this new flat.

In [28]:
# Create the new features matrix X with shape (5,4)
# Print it to make sure the shape is (5,4)

new_flat = np.array([
    [1, 3000, 5, 1]
])

X2 = np.vstack((X, new_flat))

X2.shape

(5, 4)

In [29]:
# Create the new y with shape (5,1)

y2 = np.vstack((y, np.array([700])))
y2

array([[244],
       [671],
       [504],
       [510],
       [700]])

👉 Let's try to predict the price of a 6th flat from our updated model.
To do so, try solving $\boldsymbol \theta$ from $\boldsymbol X \cdot \boldsymbol \theta = \boldsymbol y$ using [`numpy.linalg.solve`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html).

😲 What happens? Try to understand why you get an error. Then, open the explanation below the cell.

In [30]:
np.linalg.solve(X2, y2)

LinAlgError: Last 2 dimensions of the array must be square

<details>
    <summary><i>Explanations</i></summary>

$ \large \boldsymbol X$ is not a square matrix

$ \large  \rightarrow$ therefore it cannot be inverted: $ \large  \boldsymbol X^{-1}$ does not exist
 
$ \large  \rightarrow$ $ \large \boldsymbol \theta$ cannot be computed from $ \large  \boldsymbol y = \boldsymbol X \cdot \boldsymbol \theta$
    
😕 Our initial approach — finding a closed-form mathematical formula to compute the predicted price of a flat as a linear combination of only 3 features — **does not hold** for our 5 observed flats.

😉 ***Trust the process!*** 

$ \large  \rightarrow$ Instead, in the coming weeks we will learn methods to **approximate** the price of a flat based on these features.

For instance, instead of solving $\large  \boldsymbol y = \boldsymbol X \cdot \boldsymbol \theta$, we can find $ \large  \hat{\boldsymbol \theta}$ that minimizes the error $ \large \boldsymbol e = \boldsymbol X \cdot \hat{\boldsymbol \theta} - \boldsymbol y$: this approach is called a **Linear Regression model**

This new estimator can then be used to give an **approximate** prediction of the price for any new flat with $ \large  \hat y_{flat_6} = \boldsymbol x_{flat_6} \cdot \hat{\boldsymbol \theta}$

</details>

🏁 Congratulations!

💾 Don't forget to commit and push your notebook before moving on to the next challenge!